require('dotenv').config();
const fs = require('fs');
const path = require('path');

const config = {
    CONTRACT_ADDRESS: process.env.CONTRACT_ADDRESS,
    TARGET_CHAIN_ID: process.env.CHAIN_ID,
    TARGET_CHAIN_NAME: process.env.CHAIN_NAME,
    TARGET_RPC_URL: process.env.RPC_URL,
    TARGET_EXPLORER: process.env.EXPLORER_URL
};

const content = `// This file is auto-generated by scripts/sync_config.js
window.GAME_CONFIG = ${JSON.stringify(config, null, 4)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'config.js'), content);
console.log('Successfully synced config from .env to config.js');
